/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Auditoria {
  accion: string;
  actor_id: string | null;
  actor_tipo: string;
  detalle: Generated<Json>;
  entidad: string | null;
  entidad_id: string | null;
  id: Generated<Int8>;
  ip: string | null;
  ocurrido_en: Generated<Timestamp>;
  user_agent: string | null;
}

export interface Configuracion {
  actualizado_en: Generated<Timestamp>;
  clave: string;
  descripcion: Generated<string>;
  valor: Json;
}

export interface HorarioLaboral {
  creado_en: Generated<Timestamp>;
  dia_semana: number;
  hora_fin: string;
  hora_inicio: string;
  id: Generated<string>;
}

export interface Servicio {
  activo: Generated<boolean>;
  actualizado_en: Generated<Timestamp>;
  creado_en: Generated<Timestamp>;
  descripcion: Generated<string>;
  duracion_min: number;
  id: Generated<string>;
  mostrar_precio: Generated<boolean>;
  nombre: string;
  orden: Generated<number>;
  politica_reserva: Generated<string>;
  precio_cop: number | null;
  slug: string;
  visible_en_landing: Generated<boolean>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface TwoFactor {
  backupCodes: string;
  failedVerificationCount: number | null;
  id: string;
  lockedUntil: Timestamp | null;
  secret: string;
  userId: string;
  verified: boolean | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  twoFactorEnabled: boolean | null;
  updatedAt: Generated<Timestamp>;
}

export interface Usuario {
  activo: Generated<boolean>;
  creado_en: Generated<Timestamp>;
  rol: string;
  user_id: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  auditoria: Auditoria;
  configuracion: Configuracion;
  horario_laboral: HorarioLaboral;
  servicio: Servicio;
  session: Session;
  twoFactor: TwoFactor;
  user: User;
  usuario: Usuario;
  verification: Verification;
}
