/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Abono {
  anulado_en: Timestamp | null;
  anulado_por: string | null;
  confirma_saldo_a_favor: Generated<boolean>;
  creado_en: Generated<Timestamp>;
  fecha: string;
  id: Generated<string>;
  medio: string;
  motivo_anulacion: string | null;
  referencia: Generated<string>;
  registrado_por: string | null;
  tratamiento_id: string;
  valor: number;
}

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Auditoria {
  accion: string;
  actor_id: string | null;
  actor_tipo: string;
  detalle: Generated<Json>;
  entidad: string | null;
  entidad_id: string | null;
  id: Generated<Int8>;
  ip: string | null;
  ocurrido_en: Generated<Timestamp>;
  user_agent: string | null;
}

export interface Bloqueo {
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  dia_completo: Generated<boolean>;
  fin: Timestamp;
  id: Generated<string>;
  inicio: Timestamp;
  motivo: Generated<string>;
}

export interface CasoGaleria {
  actualizado_en: Generated<Timestamp>;
  consentimiento_imagen_id: string | null;
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  descripcion: Generated<string>;
  estado: Generated<string>;
  id: Generated<string>;
  imagen_antes_id: string;
  imagen_despues_id: string;
  orden: Generated<number>;
  procedimiento: string;
  publicado_en: Timestamp | null;
  publicado_por: string | null;
  servicio_id: string | null;
}

export interface Cita {
  actualizada_en: Generated<Timestamp>;
  creada_en: Generated<Timestamp>;
  estado: string;
  fin: Timestamp;
  id: Generated<string>;
  inicio: Timestamp;
  notas_internas: Generated<string>;
  origen: string;
  paciente_id: string;
  revision: string | null;
  revision_resuelta_en: Timestamp | null;
  revision_resuelta_por: string | null;
  servicio_id: string;
  vista_en: Timestamp | null;
}

export interface CitaEvento {
  actor_id: string | null;
  actor_tipo: string;
  antes: Json | null;
  cita_id: string;
  despues: Json | null;
  detalle: Generated<Json>;
  id: Generated<Int8>;
  ocurrido_en: Generated<Timestamp>;
  tipo: string;
}

export interface Configuracion {
  actualizado_en: Generated<Timestamp>;
  clave: string;
  descripcion: Generated<string>;
  valor: Json;
}

export interface Consentimiento {
  aceptado_en: Generated<Timestamp>;
  aceptante_celular: string | null;
  aceptante_documento: string | null;
  aceptante_nombre: string | null;
  cita_id: string | null;
  id: Generated<string>;
  ip: string | null;
  origen: string;
  paciente_id: string | null;
  texto: string;
  texto_sha256: string;
  tipo: string;
  user_agent: string | null;
  version: string;
}

export interface ConsentimientoImagen {
  archivo_clave: string | null;
  archivo_tipo: string | null;
  creado_en: Generated<Timestamp>;
  en_fisico: Generated<boolean>;
  fecha_firma: string;
  id: Generated<string>;
  notas: Generated<string>;
  paciente_id: string;
  registrado_por: string | null;
  verificado_por: string | null;
}

export interface HorarioLaboral {
  creado_en: Generated<Timestamp>;
  dia_semana: number;
  hora_fin: string;
  hora_inicio: string;
  id: Generated<string>;
}

export interface Imagen {
  alto: number;
  ancho: number;
  bytes: number;
  clave_original: string;
  creado_en: Generated<Timestamp>;
  formato: string;
  id: Generated<string>;
  sha256: string;
  subido_por: string | null;
}

export interface ImagenVariante {
  alto: number;
  ancho: number;
  bytes: number;
  clave: string;
  creado_en: Generated<Timestamp>;
  formato: string;
  id: Generated<string>;
  imagen_id: string;
}

export interface IntentoIngreso {
  bloqueado_hasta: Timestamp | null;
  fallidos: Generated<number>;
  ultimo_fallo: Timestamp | null;
  usuario: string;
}

export interface IntentoVerificacion {
  creado_en: Generated<Timestamp>;
  exitoso: boolean;
  id: Generated<Int8>;
  ip: string | null;
}

export interface Paciente {
  actualizado_en: Generated<Timestamp>;
  celular: string | null;
  celular_verificado_en: Timestamp | null;
  correo: string | null;
  creado_en: Generated<Timestamp>;
  estado: Generated<string>;
  fecha_nacimiento: string | null;
  fusionado_con: string | null;
  fusionado_en: Timestamp | null;
  id: Generated<string>;
  nombre: string;
  notas: Generated<string>;
  numero_documento: string | null;
  telefono: string | null;
  tipo_documento: string | null;
}

export interface PacienteCartera {
  abonado: number | null;
  deuda: number | null;
  estado_pago: string | null;
  paciente_id: string | null;
  proxima_cita: Timestamp | null;
  saldo: number | null;
}

export interface PacienteEvento {
  actor_id: string | null;
  actor_tipo: string;
  cambios: Generated<Json>;
  id: Generated<Int8>;
  ocurrido_en: Generated<Timestamp>;
  paciente_id: string;
  tipo: string;
}

export interface RateLimit {
  count: number;
  id: string;
  key: string;
  lastRequest: Int8;
}

export interface Servicio {
  activo: Generated<boolean>;
  actualizado_en: Generated<Timestamp>;
  creado_en: Generated<Timestamp>;
  descripcion: Generated<string>;
  duracion_min: number;
  id: Generated<string>;
  mostrar_precio: Generated<boolean>;
  nombre: string;
  orden: Generated<number>;
  politica_reserva: Generated<string>;
  precio_cop: number | null;
  slug: string;
  visible_en_landing: Generated<boolean>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface SolicitudReserva {
  celular: string;
  cita_id: string | null;
  consentimiento_sha256: string;
  consentimiento_version: string;
  correo: string | null;
  creada_en: Generated<Timestamp>;
  estado: Generated<string>;
  expira_en: Timestamp;
  id: Generated<string>;
  inicio: Timestamp;
  ip: string | null;
  nombre: string;
  numero_documento: string | null;
  servicio_id: string;
  tipo_documento: string | null;
  token_sha256: string;
  user_agent: string | null;
  verificada_en: Timestamp | null;
}

export interface TextoAutorizacion {
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  demostracion: Generated<boolean>;
  orden: Generated<Int8>;
  texto: string;
  version: string;
}

export interface Tratamiento {
  actualizado_en: Generated<Timestamp>;
  costo_inicial: number;
  costo_total: number;
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  descripcion: Generated<string>;
  estado: Generated<string>;
  fecha_fin: string | null;
  fecha_inicio: string | null;
  id: Generated<string>;
  notas: Generated<string>;
  paciente_id: string;
  servicio_id: string | null;
  valor_realizado: number | null;
}

export interface TratamientoEvento {
  actor_id: string | null;
  antes: Json | null;
  despues: Json | null;
  id: Generated<Int8>;
  motivo: string | null;
  ocurrido_en: Generated<Timestamp>;
  tipo: string;
  tratamiento_id: string;
}

export interface TratamientoSaldo {
  abonado: number | null;
  base: number | null;
  estado: string | null;
  estado_pago: string | null;
  paciente_id: string | null;
  saldo: number | null;
  tratamiento_id: string | null;
}

export interface TwoFactor {
  backupCodes: string;
  failedVerificationCount: number | null;
  id: string;
  lockedUntil: Timestamp | null;
  secret: string;
  userId: string;
  verified: boolean | null;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  twoFactorEnabled: boolean | null;
  updatedAt: Generated<Timestamp>;
  username: string | null;
}

export interface Usuario {
  activo: Generated<boolean>;
  creado_en: Generated<Timestamp>;
  creado_por: string | null;
  debe_cambiar_contrasena: Generated<boolean>;
  rol: string;
  user_id: string;
}

export interface VerificacionCelular {
  celular: string;
  codigo_hmac: string;
  consumida_en: Timestamp | null;
  creada_en: Generated<Timestamp>;
  expira_en: Timestamp;
  id: Generated<string>;
  intentos: Generated<number>;
  ip: string | null;
  solicitud_id: string | null;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  abono: Abono;
  account: Account;
  auditoria: Auditoria;
  bloqueo: Bloqueo;
  caso_galeria: CasoGaleria;
  cita: Cita;
  cita_evento: CitaEvento;
  configuracion: Configuracion;
  consentimiento: Consentimiento;
  consentimiento_imagen: ConsentimientoImagen;
  horario_laboral: HorarioLaboral;
  imagen: Imagen;
  imagen_variante: ImagenVariante;
  intento_ingreso: IntentoIngreso;
  intento_verificacion: IntentoVerificacion;
  paciente: Paciente;
  paciente_cartera: PacienteCartera;
  paciente_evento: PacienteEvento;
  rateLimit: RateLimit;
  servicio: Servicio;
  session: Session;
  solicitud_reserva: SolicitudReserva;
  texto_autorizacion: TextoAutorizacion;
  tratamiento: Tratamiento;
  tratamiento_evento: TratamientoEvento;
  tratamiento_saldo: TratamientoSaldo;
  twoFactor: TwoFactor;
  user: User;
  usuario: Usuario;
  verificacion_celular: VerificacionCelular;
  verification: Verification;
}
